// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:77b56ea8-0f24-4bf3-984d-06259dc6f8c1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Iol0FUUjY",
    "aws_user_pools_web_client_id": "1pm7rphgmov87fgue068uocf7i",
    "oauth": {}
};


export default awsmobile;
